name: build-and-deploy

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pack-java-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Maven
        working-directory: ./ProductManager
        run: mvn package

      - name: Save JAR Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ProductManager-0.0.1-SNAPSHOT.jar
          path: ./ProductManager/target/ProductManager-0.0.1-SNAPSHOT.jar

  validate-packer-template:
    runs-on: ubuntu-latest
    needs: pack-java-jar
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v2.0.0
        with:
          version: latest

      - name: Download JAR Artifact
        uses: actions/download-artifact@v2
        with:
          name: ProductManager-0.0.1-SNAPSHOT.jar
          path: /tmp

      - name: Copy JAR Artifact to Packer Directory
        run: cp /tmp/ProductManager-0.0.1-SNAPSHOT.jar scripts/

      - name: Format Packer Template
        run: packer fmt scripts/java.pkr.hcl

      - name: Validate Packer Template
        run: packer validate scripts/java.pkr.hcl


  build-ami:
    runs-on: ubuntu-latest
    needs: validate-packer-template
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v2.0.0
        with:
          version: latest

      - name: Build Image with Packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
        run: packer build scripts/java.pkr.hcl