name: build-and-deploy

on:
  pull_request:
    branches:
      - main
      - a07

jobs:
  validate-packer-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v2.0.0
        with:
          version: latest

      - name: Format Packer Template
        run: packer fmt scripts/app.pkr.hcl



