name: build ami after merge

on:
  push:
    branches:
      - main
      - a07

jobs:
  pack-java-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkoutcode
        uses: actions/checkout@v2

      - name: BuildwithMaven
        working-directory: .
        run: mvn -B package --file pom.xml

  build-ami:
    runs-on: ubuntu-latest
    needs: pack-java-jar
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v2.0.0
        with:
          version: latest

      - name: Build Image with Packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
        run: packer build scripts/app.pkr.hcl

