name: build ami after merge

on:
  push:
    branches:
      - main
      - modify-a05
      - new-debug-a05

jobs:
  pack-java-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Maven
        working-directory: ./ProductManager
        run: mvn package

      - name: Save JAR Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ProductManager-0.0.1-SNAPSHOT.jar
          path: ./ProductManager/target/ProductManager-0.0.1-SNAPSHOT.jar

  build-ami:
    runs-on: ubuntu-latest
    needs: pack-java-jar
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v2.0.0
        with:
          version: latest

      - name: Download JAR Artifact
        uses: actions/download-artifact@v2
        with:
          name: ProductManager-0.0.1-SNAPSHOT.jar
          path: /tmp

      - name: Copy JAR Artifact to Packer Directory
        run: cp /tmp/ProductManager-0.0.1-SNAPSHOT.jar scripts/

      - name: Build Image with Packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-1
        run: packer build scripts/app.pkr.hcl

