name: build-and-deploy

on:
  pull_request:
    branches:
      - main
      - modify-a05

jobs:
  validate-packer-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v2.0.0
        with:
          version: latest

      - name: touch jar
        run: touch /tmp/ProductManager-0.0.1-SNAPSHOT.jar

      - name: Format Packer Template
        run: packer fmt scripts/app.pkr.hcl

      - name: Validate Packer Template
        run: packer validate scripts/app.pkr.hcl